export const Routes = {
	// // pages
	// Presentation: { path: "/" },
	// DashboardOverview: { path: "/" },
	Search: { path: "/cari-dokumen" },
	AddDocument: { path: "/tambah-dokumen" },
	EditDocument: { path: "/ubah-dokumen" },
	Upgrade: { path: "/upgrade" },
	Billing: { path: "/billing" },
	Invoice: { path: "/invoice" },
	Signin: { path: "/sign-in" },
	Signup: { path: "/sign-up" },
	ForgotPassword: { path: "/forgot-password" },
	ResetPassword: { path: "/reset-password" },
	Lock: { path: "/lock" },
	NotFound: { path: "/404" },
	ServerError: { path: "/500" },

	SuratMasuk: { path: "/surat-masuk" },
	SuratKeluar: { path: "/surat-keluar" },
	PaketKonsultasi: { path: "/paket-konsultasi" },
	Kontrak: { path: "/kontrak" },
	Ded: { path: "/ded" },
	JustifikasiTeknis: { path: "/justifikasi-teknis" },
	Rpb: { path: "/rpb" },
	PadatKarya: { path: "/padat-karya" },
	UndangUndang: { path: "/undang-undang" },
	PeraturanMenteri: { path: "/peraturan-menteri" },
	SuratEdaran: { path: "/surat-edaran" },
	Keputusan: { path: "/keputusan" },
	SpesifikasiUmumKhusus: { path: "/spesifikasi-umum-khusus" },
	ManualPelaksanaan: { path: "/manual-pelaksanaan" },
	Sop: { path: "/sop" },
	Spt: { path: "/spt" },
	LaporanAmp: { path: "/laporan-amp" },
	LaporanEmonitoring: { path: "/laporan-emonitoring" },

	// components
	Accordions: { path: "/components/accordions" },
	Alerts: { path: "/components/alerts" },
	Badges: { path: "/components/badges" },
	Widgets: { path: "/widgets" },
	Breadcrumbs: { path: "/components/breadcrumbs" },
	Buttons: { path: "/components/buttons" },
	Forms: { path: "/components/forms" },
	Modals: { path: "/components/modals" },
	Navs: { path: "/components/navs" },
	Navbars: { path: "/components/navbars" },
	Pagination: { path: "/components/pagination" },
	Popovers: { path: "/components/popovers" },
	Progress: { path: "/components/progress" },
	Tables: { path: "/components/tables" },
	Tabs: { path: "/components/tabs" },
	Tooltips: { path: "/components/tooltips" },
	Toasts: { path: "/components/toasts" },
	WidgetsComponent: { path: "/components/widgets" },
};
